:icons: font
:highlightjs-theme: solarized_dark
:toc: left
:toclevels: 3
:sectlinks:
:examples-dir: ../../test/java
:github: https://github.com/ssouris/spring-tutorials

== Introduction to Spring RestTemplate - Series 1

=== What is RestTemplate?

RestTemplate is Spring's central class for synchronous client-side HTTP access.
It's meant to simplify communication with HTTP servers and enforce RESTful principles.

Be default RestTemplate relies on standard JDK facilities to establish HTTP connections.
You can switch to use different HTTP library like

* Apache HttpComponents
* Netty
* OkHttp

though the HttpAccessor.setRequestFactory(org.springframework.http.client.ClientHttpRequestFactory) property.

Internally the template uses HttpMessageConverter instances to convert HTTP messages to and from POJOs.
Converters for the main mime types are registered by default but you can also register additional converters
via
setMessageConverters(java.util.List<org.springframework.http.converter.HttpMessageConverter<?>>).

This template uses

* SimpleClientHttpRequestFactory and
* DefaultResponseErrorHandler

as default strategies for creating HTTP connections or handling HTTP errors, respectively.
These defaults can be overridden through

* HttpAccessor.setRequestFactory(org.springframework.http.client.ClientHttpRequestFactory) and
* setErrorHandler(org.springframework.web.client.ResponseErrorHandler) respectively.

=== Using RestTemplate

==== GET
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=GET]
----

==== POST
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=POST]
----

==== PUT
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=PUT]
----

==== DELETE
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=DELETE]
----

==== OPTIONS
[source,java,indent=0]
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=OPTIONS_API_CALL]

=== Get Location
[source,java,indent=0]
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=getLocation]

=== Get Headers
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=getHeaders]
----

=== Working With JsonArray response (List of things)
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=WorkWithListOfThings]
----

=== Adding Query or Path params
[source,java,indent=0]
----
include::{examples-dir}/com/yetanotherdevblog/RestTemplateTest.java[tags=addQueryOrPathParams]
----
<1> Using UriComponentsBuilder to build/encode the url
<2> Using RestTemplate API

=== Finishing First Series
This was basic stuff about RestTemplate.
In next series I am gonna dive into more fine-grained details of how to customize RestTemplate behaviour like

* Setting Timeouts
* Send Custom Header
* Follow/Unfollow Redirects
* Basic Authentication with RestTemplate
* Handling JSON body with Jackson
* Utilizing JsonView
* Error Handling
* MessageConverters

and much more

Thanks for reading. As always you can find the code at {github}[Github]